/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sanya.dany.dolinskiy (https://sketchfab.com/sanya.dany.dolinskiy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soviet-furniture-511979282b0d497d87fc9d874ac320de
Title: soviet furniture
*/

import React, { useRef } from 'react'
import { MeshReflectorMaterial, useGLTF, useTexture } from '@react-three/drei'
import { LinearEncoding } from "@react-three/drei/helpers/deprecated"

export function Cude2(props) {
  const { nodes, materials } = useGLTF('/assets/models/soviet_furniture.glb')
  return (
    <group {...props} dispose={null} position={[0, 0, 0]}
    scale={50}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box001_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box002_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box003_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box004_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box005_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box006_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box007_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box008_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box009_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box010_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box011_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box012_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Box013_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Cylinder001_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Cylinder002_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Cylinder003_Material_#25_0'].geometry}
          material={materials.Material_25}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
      <mesh rotation={[-Math.PI / 2, 0, 0]} position-y={-0.4}>
        <planeGeometry args={[300, 300]} />
        <MeshReflectorMaterial
          blur={[300, 100]}
          resolution={2048}
          mixBlur={1}
          mixStrength={40}
          roughness={1}
          depthScale={1.2}
          minDepthThreshold={0.4}
          maxDepthThreshold={1.4}
          color="#ffffff"
          metalness={0.5}
        />
      </mesh>
    </group>
  )
}

// useGLTF.preload('/assets/models/soviet_furniture.glb')
